### ISSUE TITLE
Building presonalized filters

### ISSUE THREAD

**Issue by anleopa** [KarchinLab/open-cravat#89] opened 2022-01-22 13:04 UTC
I am trying to build a personalized filter using the GUI and I have found a restriction... I cannot combine different boolean operands. For example, if I want to build the following structure...
Filter_1 OR Filter_2 OR (Filter_3 AND Filter_4)

When I try to change the operand, all the operands are automatically changed. This does not make much sense to me due to it is possible to use ( ). If all the operands must be the same, the brackets don't have any functionality.

Is there any other way of building personalized filter queries?

**Comment by rkimoakbioinformatics** [comment] 2022-01-22 16:25
Thanks for letting us know. It was a bug. run.opencravat.org has been patched with a fix. Are you using a local copy of OpenCRAVAT or run.opencravat.org?

**Comment by anleopa** [comment] 2022-01-22 16:44
I am using a local copy

**Comment by rkimoakbioinformatics** [comment] 2022-01-22 16:59
The fix has been pushed to 2.2.8 branch and will be included in the next release. If you want to apply it on your copy for now, then run `oc config system` and `package_path` of its output shows the location of your OpenCRAVAT. Go to that folder and its subfolder `webresult/nocache/css`. Replace `style.css` in the folder with the attached one (uncompress it to get style.css). Then, see if the problem is gone.

[style.zip](https://github.com/KarchinLab/open-cravat/files/7918773/style.zip)

**Comment by anleopa** [comment] 2022-01-22 17:17
Great! It works now. Thanks a lot :)

**Comment by rkimoakbioinformatics** [comment] 2022-01-22 17:31
Great!

**Closed by rkimoakbioinformatics** 2022-01-22 17:31 UTC

**Comment by skchronicles** [comment] 2022-05-10 15:48
I have also noticed the same behavior. Thank you for patching the issue in 2.2.8. 

@rkimoakbioinformatics 
I just have a quick question. Are you planning on creating an official release for 2.2.8? I see that you currently do not have a release for that patch at the moment on Github; however, I do see a tagged branch containing changes. Is that version 
 (2.2.8) stable?
