### ISSUE TITLE
Gnomad 3 annotator

### ISSUE THREAD

**Issue by cheanney** [KarchinLab/open-cravat#179] opened 2023-08-25 20:41 UTC
We have come across several variants that possess gnomad2 annotations but are unable to locate their corresponding entries on https://gnomad.broadinstitute.org/. Here are two illustrations (provided in hg19 coordinates):

chr10 60221 T A
chr10 60227 C G

Thanks in advance.

Anney

**Comment by kmoad** [comment] 2024-02-23 19:56
Duplicate of https://github.com/KarchinLab/open-cravat/issues/179

**Closed by kmoad** 2024-02-23 19:56 UTC
